api.prefix.v1=api/v1

#===========================================================================
#azure configurations
#============================================================================
apps.azure.storage.container.name=""
apps.azure.storage.connection.string=""
apps.azure.endpoint.url=""